### ISSUE TITLE
A few remaining issues before deploying easter.

### ISSUE THREAD

**Issue by jhcole** [FozLand/holiday#1]
1. The gravity reset on the stripped egg could be dangerous. I image a player's gravity being set very low. Then they jump as high as they can and at the top of their jump gravity is reset to 1. This could be a nasty surprise. How big of a problem do you think it would be to never reset to normal? So basically require the user to use a vanilla egg, die, or log out to reset.

2. I don't understand the egg_night code. Can you explain how it works. Particularly how the constants 0.47 and 0.4 were choosen?

3. mese tools are in the rare tools list while diamond tools are in the uncommon tools list. I think this is correct in terms of rarity, but diamond tools are better than mese tools. I just want to be sure the choice is intentional.

4. We may want to adjust the egg drop probabilities. As it stands now, the first four will drop ~40% of the time, the next three ~50% of the time, and the last six 10% of the time. Also I think maybe space, mario, and speed should be in the same group.

Thoughts?

**Comment by mootpoint** [comment]
1.)  I agree, however if the gravity is above 2 it probably should reset or it would kill them, i will change the code
2.) for the egg night code
override_day_night_ratio(ratio or nil)`

    * `0`...`1`: Overrides day-night ratio, controlling sunlight to a specific amount
    * `nil`: Disables override, defaulting to sunlight based on day-night cycle
you can only adjust the light values between 0 and 1, the api is not very clear, 
this code was adapted from the lightcorrect mod that makes it so that players can see better at night.

now from what i understand 0 is no light an 1 is full sunlight so 0.47 would be roughly dusk/dawn times
the adjustment on light is modified by 40 percent brighter if the light is dark. ie. (closer to 0)
and if not it makes it darker.
3.) yes i made it this way since mese is rarer than diamond
4.) i didnt realize that about the egg drops, i will ook at that, i agree about speed mario and space being in the same group.
